# Generated by Django 5.1.4 on 2024-12-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('variant_detection', 'Variant Detection'), ('sequence_alignment', 'Sequence Alignment'), ('orf_detection', 'ORF Detection')], max_length=50)),
                ('input_sequence_1', models.TextField()),
                ('input_sequence_2', models.TextField(blank=True, null=True)),
                ('result', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
