# Generated by Django 5.1.4 on 2024-12-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='analysis_type',
            field=models.CharField(choices=[('variant_detection', 'Variant Detection'), ('sequence_alignment', 'Sequence Alignment'), ('orf_detection', 'ORF Detection')], max_length=19),
        ),
    ]
