# Generated by Django 5.1.4 on 2024-12-19 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_analysisresult_analysis_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisresult',
            name='analysis_type',
        ),
    ]
